### PR TITLE
Removes support for very old EOL Active Record 5.0 and older

### PR DESCRIPTION
**Pull request by jdufresne**
This commit drops support for ancient versions of Active Record that are EOL. These versions fail in CI, slowing down contributions from new developers. So keeping these ancient version of Active Record is a maintenance burden.

Assuming Active Record 5.1 or newer, the code can remove all version conditionals. All mentions of older versions of Active Record and Ruby were removed.

Active Record 5.1 was release April 27, 2017. So this change still goes very far back to support older versions.

Reducing the total testing matrix also reduces the CI time, thus providing faster feedback to new contributors.

For a more detailed description on the Rails maintenance policy and supported versions, see:

https://rubyonrails.org/maintenance

### CODE REVIEW

**Comment by albus522** [comment]
EOL is not a good enough reason to remove support for something that isn't broken. Master branch is currently green for all these tests.

**Comment by jdufresne** [comment]
> EOL is not a good enough reason to remove support for something that isn't broken. 

The commit explains why this goes beyond just EOL.

> Master branch is currently green for all these tests.

That is not what I see:

Screenshot 2024-09-09 at 07-19-00 collectiveidea_delayed_job_active_record ActiveRecord backend integration for DelayedJob 3 0


Further, as delayed job is very infrequently released. Users that are on ancient versions of Rails can continue using these older versions without any change to their workflow.

**Comment by albus522** [comment]
Expand that. Canary builds are allowed to be red and all those are jruby and future rails/ruby.
Screenshot 2024-09-09 at 10 23 45 AM

**Comment by jdufresne** [comment]
FWIW, having CI routinely fail is confusing to new contributors such as myself. When opening a PR, it isn't clear if the failure is intended or something introduced in my work.

**Comment by albus522** [comment]
That is a limitation of Github Actions. We are not going skip running lookaheads and canary is a pretty common naming convention for early testing.

**Pull request closed without merging**
