### PR TITLE
Fix incompatibility with bootsnap

### PR DESCRIPTION
**Pull request by dsander**
When using bootsnap in production it tries to compile the migration
files, but fails because the files are actually erb and thus not a
valid ruby file.

### CODE REVIEW

**Comment by albus522** [comment]
What specific error did you run into and under what configuration? I have not seen where bootstrap is trying to compile these files.

**Comment by dsander** [comment]
The error was that files were named `.rb` while actually being `.erb` templates and not containing valid ruby syntax.

**Comment by albus522** [comment]
I was asking for the actual error message as I can not reproduce your issue. Those files are never required by ruby and therefore should never be touched by bootsnap. A backtrace from the error would also be helpful.

**Comment by dsander** [comment]
Sorry you are right, at Huginn we have been running on a fork that uses this commit: https://github.com/dsander/delayed_job_active_record/commit/55535e2d310665e2a5348bedc2b3c29fde287bb1 I kind of forgot about that change and without it (and the latest master branch) it works without issues.

Kind of unrelated question, we conditionally need to modify the `reserve_sql_strategy`, but since the Railtie is running `after_initialize` we can not do that in a Rails initializer. 

Would you accept a PR that adds a `ActiveSupport.run_load_hooks` call like this: https://github.com/dsander/delayed_job_active_record/commit/0b433cc38cec67b911f3f07dab8caa61b3202990 ?

Thanks for your recent work on this gem!

**Comment by albus522** [comment]
I am reasonable sure `after_initialize` hooks are run in the order in which they are defined. So if you add an `after_initialize` in your app that makes the changes you want, it should run after the one defined in DJ runs.

**Comment by albus522** [comment]
Thank you for pointing out the `reserve_sql_strategy` issue. I need to update the documentation about that. I knew that change had something we were missing.

**Comment by dsander** [comment]
> it should run after the one defined in DJ runs.

Thanks that seems to work. 👍

**Comment by albus522** [comment]
@dsander I have been picking away at #149 slowly and would be curious to know what caused you to choose the old lock format.

**Comment by dsander** [comment]
We are only using the old lock strategy on mysql. Here is the original issue and reproduction: https://github.com/huginn/huginn/issues/977#issuecomment-133534593. I believe we tested it against Postgres as well and did not have any issues with the optimized strategy.

**Comment by albus522** [comment]
Thank you for digging that up.

**Pull request closed without merging**
