### PR TITLE
Allow rails 5.1

### PR DESCRIPTION
**Pull request by matthewrudy**

### CODE REVIEW

**Comment by matthewrudy** [comment]
The tests fail on jruby9.
Seems the jdbc gems aren't working with Rails 5.0+

I guess it needs to use https://rubygems.org/gems/activerecord-jdbcpostgresql-adapter/versions/5.0.pre1?

**Comment by jaredbeck** [comment]
5.1 final is out now, maybe try:

```diff
- gem 'activerecord', ">= 5.1.0.beta1", "< 5.2"
+ gem 'activerecord', '~> 5.1.0'
```

Maybe that'll fix CI? (fingers crossed)

**Comment by nynhex** [comment]
Any update on getting this merged and a new release cut?  Need 5.1 support too.  Happy to help with the PR if need be.

**Comment by matthewrudy** [comment]
@jaredbeck I think that the format is fine,
I made a wording change to kick off a new build anyway.

Will see if it works

**Comment by matthewrudy** [comment]
I'm just about to merge using my fork for my own project

``` ruby
gem 'delayed_job', github: 'gogovan/delayed_job', branch: 'rails-5.1'
gem 'delayed_job_active_record', github: 'gogovan/delayed_job_active_record', branch: 'rails-5.1'
```

Will see how that goes.

**Comment by laserlemon** [comment]
@matthewrudy Thank you! Do you have any insight into the failures we're seeing on Travis for a handful of the build combinations?

**Comment by laserlemon** [comment]
Sorry, I see now that you (and other folks) _do_ have insight. It was just all lost in the sea of Coveralls comments (which I've now disabled).

**Comment by jeremylightsmith** [comment]
Any idea when a new version that supports rails 5.1 will be released? i would really like to upgrade rails, but can't because of this library...

**Comment by matthewrudy** [comment]
@jeremylightsmith I'm just using my forks via git

```
gem 'delayed_job', github: 'gogovan/delayed_job', branch: 'rails-5.1'
gem 'delayed_job_active_record', github: 'gogovan/delayed_job_active_record', branch: 'rails-5.1'
```

seems to work fine.

**Comment by jaredbeck** [comment]
Rails 5.1 support has been released in DJAR 4.1.2 AFAICT

Steve, re: your commit message on https://github.com/collectiveidea/delayed_job_active_record/commit/75609d800179b52bdf8b710f735dd4d321edba56

> Allow failure on JRuby for PostgreSQL and MySQL under Rails 5.1
> JRuby just isn't ready for Rails 5.1. The adapters need work and feel
stalled.

As an MRI user, I'm biased, but I'm glad you didn't let the JRuby adapters hold you up. Thanks for your work on this.

**Comment by laserlemon** [comment]
Yes, there are new releases for both `delayed_job` and `delayed_job_active_record`, in both cases to support Rails 5.1. Please report any issues you come across. Thank you!

**Pull request merged**
