### PR TITLE
max parallel execution configurable for each queue

### PR DESCRIPTION
**Pull request by emmanueldelmas**
This change with another on delayed_job permits to configure a limit of concurrent execution of a queue.
Follows an example of configuration in the config/initializers/delayed_job.rb where "import" and "export" are queue names.
`Delayed::Worker.default_max_workers_by_queue = 3`
`Delayed::Worker.max_workers_by_queue = {"import" => 1, "export" => 2}`

For example, with this configuration :
1. one worker is running a job from queue import.
2. a second job from queue import is waiting a worker.
3. when the second worker is available, it does not take the second job from queue because of max_workers_by_queue

Another example :
1. If you have 4 workers available, and 20 available jobs from the queue mailer.
2. Only 3 workers will run the jobs from mailer queue.
3. The fourth worker stay available for another queue because of default_max_workers_by_queue.

This configuration permits to optimize the use of the workers, and in the same time to control that one queue don't take all available workers or that two jobs from one specific queue could not be execute in the same time.

### CODE REVIEW

**Comment by albus522** [comment]
I am unsure what you are trying to solve here. Just tell the workers you start up to work off specific queues. https://github.com/collectiveidea/delayed_job#running-jobs

**Comment by emmanueldelmas** [comment]
I wish optimize my use of the workers on the server.
In case I have 10 queues and I don't want concurrent execution of job from the same queue.
So I can create 10 workers, 1 for each queue. But it's a lot and most of the time there are no job to execute. It's a waste of memory on the server.
I can create 3 workers with 3 or 4 queues by workers. But if there are 2 jobs from 2 queues of the same worker, it means that the second job has to wait even if there are 2 workers available. It's a waste of time and a potential delay.

With this commit, I can have only 3 workers, and to be sure that :
- each worker is often running a job (no waste of memory).
- a job is execute if a worker is available (no waste of time).
- jobs from the same queue are not execute concurrently.

**Comment by albus522** [comment]
Ok. This could be useful, but there is more to account for than just `locked_by`. Off the top of my head, this would still need to account for dead or failed workers as well as execution expiration. This could easily end up deadlocking all the workers so that none of them think they should be working on anything.

**Comment by emmanueldelmas** [comment]
OK. I understand. I have just pushed a second commit to account for dead or failed workers and execution expiration.
I have based my modification on the ready_to_run request.

**Pull request closed without merging**
