### PR TITLE
In the MySQL optimized query split SELECT / UPDATE

### PR DESCRIPTION
**Pull request by bsimpson**
Given the following index on the delayed_jobs table:

CREATE INDEX delayed_job_priority ON delayed_jobs(priority,run_at);

MySQL will ignore this index, and does not support hints when doing an
UPDATE SET ... LIMIT 1; Without an index, the ordering is done via a
filesort, and can be problematic when the delayed_jobs table
becomes large (>10,000 records). This results in an increasingly long
system lock wait time to reserve the job.

By separating the SELECT from the UPDATE, we can take advantage of an
INDEX while fetching the row to lock for a reservation.

More information on SELECT ... FOR UPDATE here:
http://dev.mysql.com/doc/refman/5.7/en/innodb-locking-reads.html

More information on the issue at:
https://mrfrosti.com/2016/06/06/delayed-job-performance-tuning/

### CODE REVIEW

**Comment by albus522** [comment]
This is basically what `Delayed::Backend::ActiveRecord.configuration.reserve_sql_strategy = :default_sql` does. This strategy increases contention while running more workers. We introduced the setting to allow people to chose based on how they run things. Different people have different requirements and there is no solution that works best for all.

**Comment by bsimpson** [comment]
@albus522 Thanks for the quick response. Interesting that the :default_sql strategy increases worker contention. How many workers are typically running when contention begins to be an issue? To clarify, the :optimize_sql better lends itself to smaller table sizes and more workers, while :default_sql is better for larger table sizes with less workers?

**Comment by bsimpson** [comment]
One more question about the worker contention - is this applicable even with the index on `delayed_jobs(priority,run_at)`? Seems like the :default_sql strategy would benefit from this where the :optimize_sql strategy could not?

**Comment by albus522** [comment]
Yes, generally optimize is better for most scenarios except super large jobs tables, which is most users, and default is the old style which has its own quirks including increasing worker contention. The worker contention comes from the locking, no other worker can do anything until the lock is released. The default strategy tries to partially offset this by not locking but returning a set of potential jobs then the worker tries to lock each until one succeeds, but if enough workers are active you end up with them all fighting to get jobs instead of working on jobs.

Large jobs tables are usually, but not always, a result of creating A LOT of fast jobs the workers are just expected to slam through fast. This is NOT what DJ is optimized for. DJ is optimized for running jobs that take too long to simply run inline, for which the runtime is way more than the lock time even if the lock is a little slower.

**Pull request closed without merging**
