### PR TITLE
Add PostGIS to adapter to prevent default SQL for locking job.

### PR DESCRIPTION
**Pull request by hugueslamy**
To make the code more robust, downcase the name adapter. As shown in the PostGIS page: https://github.com/rgeo/activerecord-postgis-adapter, the adapter could be typed in any case. This is the same as Pull request #117 but a bit more flexible.

### CODE REVIEW

**Comment by hugueslamy** [comment]
uninitialized constant Rails

I'm not sure I understand why this is falling. Unrelated bug on Rails 5.0 with JRuby?

**Comment by 007** [comment]
@albus522 @hugueslamy any chance of getting this and/or #117 from @stestaub through to release? We currently have 806k jobs queued from a single task that adds to its own queue due to this duplication. We're monkeypatching but would really prefer upstream fixes.

**Comment by pleary** [comment]
I just wanted to add my support to this pull request. We're using Rails and PostGIS and were hit with delayed jobs getting picked up by two or sometimes 3 workers simultaneously. About 1% of jobs were running more than once. After deploying this fix that allows us to use the optimized PostgreSQL query, there have been zero instances of duplicates. This fix is really important for people in our boat

**Comment by jackcasey** [comment]
:+1:  Can this please be merged.

This caused havoc for months. We now see that it started exactly when we moved to PostGIS.  The 'fallback' sql is NOT an atomic way to select jobs and multiple workers can easily pick up the same job in the race condition between the select and the update :( 

Finding this known issue with a fix in a year old PR makes me cry.

**Comment by albus522** [comment]
@jackcasey The default handling is atomic, the update runs with the same where conditions as the select so the update will fail if another worker has already grabbed the job.

To answer the question of can this be merged, I have no idea, this doesn't provide any new tests to verify this even works.

**Comment by albus522** [comment]
@jackcasey no it won't. because https://github.com/collectiveidea/delayed_job_active_record/pull/124/files#diff-4dff69dae158bc1bc8b2f4f839ef5dafR136 will be count 0 and return false

**Comment by 007** [comment]
Three people have commented here that it's broken, several more on #117 (which is merged!!!) all say the same thing. 

You can say "no it won't" all you like, but you're wrong - it's not supposed to double up, but it does. My guess is that it's transactional, you're doing the select/update in a transaction and keeping it open until the job is done, so nobody sees the status change to "locked" until it's far too late and every worker N>1 has their transaction roll back.

Maybe something else is broken somewhere else, maybe it has nothing to do with dj_ar and we're all just doing something stupid - but maybe take us seriously instead of blindly dismissing us?

**Comment by laserlemon** [comment]
@albus522 Will the [line you linked to](https://github.com/collectiveidea/delayed_job_active_record/pull/124/files#diff-4dff69dae158bc1bc8b2f4f839ef5dafR136) always return `1` since that update should always succeed (even if some other worker has actually already claimed it)?

giphy

**Comment by laserlemon** [comment]
Oh, I see the `ready_scope` bit now.

homer-simpson-bush-gif

**Comment by albus522** [comment]
If you search the issues you will notice a long history of multiple workers working on the same job, which have almost always traced back to something other than the lookup and lock query. As for your transaction comment, DJ does not have a transaction wrapper around the entire job, so I can't imagine how the cause would be a blocking transaction.

As for a PR for new features go, please understand what that means to us. It means something we will have to maintain in the future because the PR submitters very rarely come back to maintain their work. Users will expect the new feature to stay working. As such, it isn't always something we want to commit to. Also this has zero tests for us to know if it works or know if it breaks. We don't have any PostGIS experts on our team. A brief search shows it is mostly Postgres but this is also using a driver we have no experience with. Learning all this is not part of our expertise. We would need someone with expertise to claim ownership and help people with questions in the future.

To be clear, I am NOT saying don't submit new things, but understand merging isn't the only thing we have to consider.

**Comment by albus522** [comment]
Sorry, I hate the cancel comment vs close PR functionality

**Comment by albus522** [comment]
Although @laserlemon already merged https://github.com/collectiveidea/delayed_job_active_record/pull/117 so closing again to clear things out

**Comment by jackcasey** [comment]
@albus522 I'm looking at it again now and you're right I can't see an issue with it, must have missed something yesterday. It's just so crazy what we're seeing... Will need to dig deeper, whether #117 fixes it for us or not. 

Anyway I apologise for jumping to conclusions and even doubling down when wrong. (I shouldn't have replied from memory on my phone last night :/). 

It's good that PostGIS will behave like Postgresql after  #117 👍

**Pull request closed without merging**
